"""Self-contained HTML reports.

One file, no external assets: the chart is embedded as a base64 PNG, styling
is inline. Rendering uses an explicit Agg canvas, so reports work headless
(cron, CI) regardless of the matplotlib backend.
"""

from __future__ import annotations

import base64
import html
import io
import pathlib
from typing import Iterable

_CSS = """
body { font-family: -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
       margin: 2rem auto; max-width: 60rem; color: #1a1a1a; }
h1 { font-size: 1.4rem; } h2 { font-size: 1.15rem; margin-top: 2.5rem; }
table { border-collapse: collapse; margin: 0.75rem 0; }
td, th { border: 1px solid #ddd; padding: 0.3rem 0.7rem; text-align: left;
         font-size: 0.9rem; }
th { background: #f5f5f5; }
img { max-width: 100%; }
.badge { display: inline-block; padding: 0.25rem 0.8rem; border-radius: 0.3rem;
         color: white; font-weight: 600; font-size: 0.95rem; }
.ok { background: #2e7d32; } .bad { background: #c62828; }
details { margin: 0.75rem 0; } summary { cursor: pointer; color: #555; }
footer { margin-top: 3rem; color: #888; font-size: 0.8rem; }
"""


def _fmt(v) -> str:
    if isinstance(v, float):
        return f"{v:.6g}"
    return html.escape(str(v))


def _figure_png(result) -> str:
    from matplotlib.backends.backend_agg import FigureCanvasAgg
    from matplotlib.figure import Figure

    from . import _plot

    if result.method in _plot._SINGLE or result.method == "capability":
        fig = Figure(figsize=(9, 4.5))
        ax = fig.subplots()
    else:
        fig = Figure(figsize=(9, 5.5))
        ax = fig.subplots(2, 1, sharex=True, gridspec_kw={"height_ratios": [2, 1]})
    FigureCanvasAgg(fig)
    _plot.render(result, ax=ax)
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=110, bbox_inches="tight")
    return base64.b64encode(buf.getvalue()).decode("ascii")


def _kv_table(mapping) -> str:
    rows = "".join(
        f"<tr><td>{html.escape(str(k))}</td><td>{_fmt(v)}</td></tr>"
        for k, v in mapping.items()
    )
    return f"<table>{rows}</table>"


def _section(result, heading: str | None = None) -> str:
    title = heading or f"{result.method} ({result.meta.get('source', '')})"
    badge = (
        '<span class="badge ok">IN CONTROL</span>'
        if result.ok
        else f'<span class="badge bad">OUT OF CONTROL - {len(result.signals)} signal(s)</span>'
    )

    signals_html = ""
    if result.signals:
        rows = "".join(
            f"<tr><td>{html.escape(s.rule)}</td><td>{html.escape(s.chart)}</td>"
            f"<td>{html.escape(', '.join(map(str, s.points)) or '-')}</td>"
            f"<td>{html.escape(s.note)}</td></tr>"
            for s in result.signals
        )
        signals_html = (
            "<h3>Signals</h3><table><tr><th>rule</th><th>chart</th>"
            f"<th>points</th><th>note</th></tr>{rows}</table>"
        )

    provenance = {**dict(result.meta), "params": dict(result.params)}
    return f"""
<h2>{html.escape(title)}</h2>
<p>{badge}</p>
<img alt="{html.escape(result.method)} chart" src="data:image/png;base64,{_figure_png(result)}">
<h3>Statistics</h3>
{_kv_table(result.stats)}
{signals_html}
<details><summary>Provenance</summary>{_kv_table(provenance)}</details>
"""


def _page(body: str, title: str) -> str:
    from ._version import __version__

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>{html.escape(title)}</title><style>{_CSS}</style></head>
<body>
<h1>{html.escape(title)}</h1>
{body}
<footer>Generated by shewhart {__version__}</footer>
</body></html>
"""


def result_to_html(result, path=None, *, title: str | None = None):
    """Render one Result as a self-contained HTML page."""
    page = _page(_section(result, heading=None), title or f"shewhart {result.method} report")
    if path is None:
        return page
    p = pathlib.Path(path)
    p.write_text(page, encoding="utf-8")
    return p


def report(results: Iterable, path=None, *, title: str = "shewhart report"):
    """Combine several Results into one self-contained HTML page.

        sw.report([r1, r2, r3], "weekly_report.html")

    The page-level banner is green only if every result is in control,
    which makes the report the visual twin of the cron exit code.
    """
    results = list(results)
    if not results:
        raise ValueError(
            "report() needs at least one Result. "
            'Example: sw.report([sw.imr(df, value="x")], "report.html")'
        )
    all_ok = all(r.ok for r in results)
    banner = (
        '<p><span class="badge ok">ALL IN CONTROL</span></p>'
        if all_ok
        else f'<p><span class="badge bad">{sum(not r.ok for r in results)} of '
        f"{len(results)} analyses signal</span></p>"
    )
    body = banner + "".join(_section(r) for r in results)
    page = _page(body, title)
    if path is None:
        return page
    p = pathlib.Path(path)
    p.write_text(page, encoding="utf-8")
    return p
